server:
  listen: 0.0.0.0:8080
  debug: true
  middlewares:
    - attach_info
    - xray
    - attach_request_id
    - maintenance_mode
    - prometheus_metrics

jwt:
  encryption_method: A128CBC-HS256     # if this key exists, will using JWE instead of JWS
  key_algo: RSA-OAEP-256
  compression_method: none             # required for JWE
  enable: true
  duration: 2591940

cache:
  provider: redis
  addr: {{ cache_addr }}
  password: {{ cache_password }}
  db: 0

cache_read_only:
  provider: redis
  addr: {{ cache_read_only_addr }}
  password: {{ cache_read_only_password }}
  db: 0

gorm:
  dialect: postgres
  connectionstring: {{ gorm_connectionstring }}

# token_generation:
#   gen_selfcare_bearer_token:
#     method: POST
#     url: {{ upstream_base_url }}/selfcare/oauth/create-token
#     timeout: 60


http_client:
  upstreams:
    timeout: 20

grpc_service:
  listen: 0.0.0.0:50052

grpc_server:
  auths_service:
    address: 127.0.0.1:50052

upstreams_api:
  cm_profile:
    method: GET
    url: {{ apigate_igw_base_url }}/subscriberidentity/commercial/api/v1/subscriberidentity/get-cm-profile?msisdn={{msisdn}}
 
keycloak:
  host: {{ keycloak_url }}
  client_id: ciam
  client_secret: 1S02Yh8a4CTgcbI0BChurYLO4QXQYr16
  realm: xl-ciam
  authorization_secret: Basic cXVhcmt1c19jbGllbnQ6ZHV3bWF0ZGlRclJQUWFvcW14RW14UzVpcHJ2SG51ZGg=
  auth_session_id_legacy: 0f0efc37-7e4b-409f-8350-690bb0b9ea17
  introspect_url: {{ keycloak_url }}/realms/xl-ciam/protocol/openid-connect/token/introspect
  iss: {{ iss_url }}
  iss_console: {{ iss_console_url }}
  super_admin_role: {{ super_admin_role_enum }}

igw_genbearer:
  method: POST
  url: {{ igw_genbearer_token_url }}/token
  client_id: DNgS7HlRIXedJ7wPaGBDwcyAqhQa
  client_secret: Df6dpwivX_MS63cx1EYhupduPw0a
  grant_type: client_credentials
  validity_period: "300"
  cache_period : 300